Event taskScreen viewModel
Assocify-Team/Assocify pull request #162
Opened 2024-04-25 16:17 UTC by ortoLover

We have just finished working on the whole event screen viewModel, we have now to work on the viewModel of the task tab. We will thus have to set the task management, like the filtering or the clicking of the tasks.
- [ ] Manage the add button
- [ ] Manage the click on association button
- [ ] Work on the filtering
- [ ] Fetch the Tasks using the API

2024-04-30 09:37 UTC, sarahbadr17 requested changes
The event tab is broken: I have this message: error on loading events.

2024-04-30 09:37 UTC, sarahbadr17 commented on app/src/main/java/com/github/se/assocify/model/entities/Task.kt
> +    val location: String = "Here",
Do we really want our Location to be a string? maybe coordinates is better?

2024-05-02 15:49 UTC, Polymeth commented on app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreen.kt
> +    viewModel: EventScreenViewModel,
nit: should have a more explicit name, like eventScreenViewModel or something

2024-05-02 15:52 UTC, Polymeth commented on app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreenViewModel.kt
> +      EventPageIndex.MAP -> {
No search in MapScreen, so I don't know how to deal with this

2024-05-02 16:06 UTC, Polymeth approved these changes
Few nit picks but overall good job :)

2024-05-02 16:06 UTC, ortoLover commented on app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreen.kt
> +    viewModel: EventScreenViewModel,
Will change now!!

2024-05-02 16:07 UTC, ortoLover commented on app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreenViewModel.kt
> +      EventPageIndex.MAP -> {
Don't we want to filter the tasks on the map depending on their name? We should talk about this later

2024-05-02 18:12 UTC, merged