Budget API structure
Assocify-Team/Assocify pull request #186
Opened 2024-04-29 21:40 UTC by zizouet

2024-04-30 15:55 UTC, sarahbadr17 requested changes
For me, we you can only work with budgetItems and in the viewmodel of the screen, I can filter each budget Item by its category. Good job !

2024-04-30 15:55 UTC, sarahbadr17 commented on app/src/main/java/com/github/se/assocify/model/entities/Budget.kt
For me, you don't need a budget entity since we already have accountingCategories or accountingSubCategories. Look into that first and tell me what you think.

2024-04-30 15:55 UTC, sarahbadr17 commented on app/src/main/java/com/github/se/assocify/model/database/BudgetAPI.kt
> +      budgetUID: String,
Is it necessary?

2024-05-01 09:34 UTC, zizouet commented on app/src/main/java/com/github/se/assocify/model/database/BudgetAPI.kt
> +      budgetUID: String,
Yes, when you need to add a line to your budget you add a budget item

2024-05-01 09:34 UTC, zizouet commented on app/src/main/java/com/github/se/assocify/model/entities/Budget.kt
I agree with you i removed it :)

2024-05-01 09:51 UTC, sarahbadr17 approved these changes
LGTM! you can merge

2024-05-01 09:53 UTC, merged