Map viewmodel
Assocify-Team/Assocify pull request #288
Opened 2024-05-14 13:16 UTC by Polymeth

WORK IN PROGRESS ;)

2024-05-17 13:34 UTC, ortoLover requested changes
Good PR!! I have checked the final result on the app and it does what it is supposed to do, there is no more the problem with the screen moving. Also the code looks clean and expected a few nitpicks everything lookks good. Good job!!

2024-05-17 13:34 UTC, ortoLover commented on app/src/main/java/com/github/se/assocify/ui/screens/event/tasktab/EventTaskViewModel.kt
> +    Log.w("mdrr: ", _uiState.value.tasks.size.toString())
You are leaving a debug message in the middle of the code.

2024-05-17 13:34 UTC, ortoLover commented on app/src/main/java/com/github/se/assocify/ui/screens/event/maptab/EventMapViewModel.kt
> +  fun fetchTasks() {
This function can be private

2024-05-17 13:34 UTC, ortoLover commented on app/src/main/java/com/github/se/assocify/ui/screens/event/maptab/EventMapViewModel.kt
> +        { _uiState.value = _uiState.value.copy(loading = false, error = "Error loading tasks") })
Check error as true here

2024-05-17 18:48 UTC, Polymeth commented on app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreenViewModel.kt
> +    if (_uiState.value.currentTab == EventPageIndex.Tasks) {
Was required for reliability, the CI didn't want the empty switch case even tho I never changed it lmao

2024-05-17 18:51 UTC, Polymeth commented on app/src/main/java/com/github/se/assocify/ui/screens/event/tasktab/EventTaskViewModel.kt
> +    Log.w("mdrr: ", _uiState.value.tasks.size.toString())
Oupsie

2024-05-17 18:52 UTC, Polymeth commented on app/src/main/java/com/github/se/assocify/ui/screens/event/maptab/EventMapViewModel.kt
> +        { _uiState.value = _uiState.value.copy(loading = false, error = "Error loading tasks") })
No error so no needs to change error

2024-05-18 12:39 UTC, ortoLover reviewed
Everything good now!!

2024-05-18 13:25 UTC, ortoLover approved these changes
Forgot to approve, you can merge now!

2024-05-18 14:31 UTC, merged