Edit a subcategory
Assocify-Team/Assocify pull request #300
Opened 2024-05-14 20:23 UTC by sarahbadr17

In AccountingDetailedScreen, you can now edit the subCategory by clicking on the edit button on the top of the page. It opens a popup where you can change the name, the year and the tag attached too.

2024-05-15 14:27 UTC, SekoiaTree requested changes
A few changes and a crash, but otherwise good!

2024-05-15 14:27 UTC, SekoiaTree commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt
> +    mutableStateOf(categoryList.filter { it.uid == subCategory.categoryUID }[0].name)
I get a crash here if I click on the edit button before everything loads. Additionally, the "No items" text looks wrong before the load. You should display a loading circle until all the data is loaded.

2024-05-15 14:27 UTC, SekoiaTree commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingViewModel.kt
> +          Log.d("BudgetViewModel", "Subcategories: $subCategoryList")
Debug code left in

2024-05-15 14:27 UTC, SekoiaTree commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingScreen.kt
> +  Log.d("AccountingScreen", "subCategoryList: $subCategoryList")
Debug code left in.

2024-05-15 14:27 UTC, SekoiaTree commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt
> +                  Text("Save")
These buttons should be dialog buttons. From some quick research, it seems like you should use the "confirm button" and the "dismiss button" of AlertDialog.

2024-05-15 14:27 UTC, SekoiaTree commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt
> +    balanceViewModel: BalanceDetailedViewModel,
nit: I don't like having two essentially identical viewmodels. They also have identical functions, but this forces us to have `when`s everywhere. However, you didn't create this system. Perhaps a problem for another PR?

2024-05-15 14:27 UTC, SekoiaTree commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt
> +                                      budgetViewModel.cancelSubCategoryEditingInBudget()
Nit: the two methods don't have the same naming pattern.

2024-05-15 14:29 UTC, SekoiaTree commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt
> +                  Text("No items for the ${balanceState.subCategory.name} sheet with these filters")
This text should be centered, for cleaniness. Same for the other "no items" text below.

2024-05-16 06:23 UTC, sarahbadr17 commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt
> +    balanceViewModel: BalanceDetailedViewModel,
Hi, I agree that it's not good practice and not even good code. I looked into implementing closed Unions in Kotlin, which can be done with a sealed class, but the code would have been even more horrendous and it would have cost me too much time for what it is. Maybe we can merge these two viewmodel, since they are practically the same. This can be another Pr, but in my opinion, it's not the priority for our app. We can do this another time for the "v2" of our project. Right now, we need to satisfy the product owners requirements,  and we would spend too much time refactoring our code.

2024-05-16 06:29 UTC, sarahbadr17 commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt
> +    mutableStateOf(categoryList.filter { it.uid == subCategory.categoryUID }[0].name)
Loading will be done in another PR! But yes, I agree, we shouldn't be able to click on it when the loading has not be done. I can add a condition for that

2024-05-16 08:57 UTC, sarahbadr17 commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt
> +                  Text("Save")
As you can see, I'm not using AlertDialog, because it's deprecated. The Dialog composable that I'm using doesn't have any parameters of this kind, so it seems that I don't have any option rather than using these Textbutton.

2024-05-16 11:31 UTC, SekoiaTree commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt
> +                  Text("Save")
AlertDialog is deprecated, but it has been replaced by BasicAlertDialog, which is *not* deprecated.

2024-05-16 11:54 UTC, SekoiaTree reviewed
Almost good! I noticed some visual stuff while testing that should just be a few lines, if you could fix those it'd be ready in my opinion!

2024-05-16 11:54 UTC, SekoiaTree commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt
Two small visual notes:
- the amount number is smaller than on the receipt screen. You should add a `style = MaterialTheme.typography.bodyMedium` to the text
- the balance item composable has some padding on the amount that the budget item doesn't have

2024-05-16 12:37 UTC, SekoiaTree approved these changes
LGTM! Good job!

2024-05-16 12:37 UTC, merged