Create budget Item Screen
Assocify-Team/Assocify pull request #319
Opened 2024-05-16 14:16 UTC by ortoLover

We already have the edit budget item screen, and we want to use it to create a create budget item screen. The objective of this screen would be of creating a new budget item and push it on the database.

- [ ] Create the UI
- [ ] Create the appearance and disappearance of the screen
- [ ] Create the functionality

2024-05-18 07:53 UTC, sarahbadr17 requested changes
Some little fixes need otherwise good!

2024-05-18 07:53 UTC, sarahbadr17 commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetPopUpScreen.kt
> +
java docs please

2024-05-18 07:53 UTC, sarahbadr17 commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetPopUpScreen.kt
> +            Text("Dismiss")
Either modify the name to cancel button or add an "cross icon button" `Icons.Default.Close` on the top right of the pop up

2024-05-18 07:53 UTC, sarahbadr17 commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetPopUpScreen.kt
> +                  Log.e("Error", budget.toString())
Debut message left?

2024-05-18 07:53 UTC, sarahbadr17 commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetPopUpScreen.kt
> +            Text("Confirm")
For me, on a small phone, the buttons are not shown. If I make the Card scrollable: `Card(
        modifier = Modifier
            .padding(16.dp)
            .testTag("editDialogBox")
            .verticalScroll(rememberScrollState()),
        shape = RoundedCornerShape(16.dp),
    )`, they appear because I can scroll down to them. However, there's a difference of vertical spacing between these buttons and the rest of the outlined text field

2024-05-18 07:53 UTC, sarahbadr17 commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetPopUpScreen.kt
> +fun BudgetPopUpScreen(budgetViewModel: BudgetDetailedViewModel) {
Bug: I can create a budget Item without a name

2024-05-18 11:36 UTC, ortoLover commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetPopUpScreen.kt
> +
Added it!!

2024-05-18 11:37 UTC, ortoLover commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetPopUpScreen.kt
> +            Text("Dismiss")
Modified to cancel, if I have time later will do a PR to transform to a cross button like in the balance screen

2024-05-18 11:37 UTC, ortoLover commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetPopUpScreen.kt
> +                  Log.e("Error", budget.toString())
Removed it!!

2024-05-18 11:52 UTC, ortoLover commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetPopUpScreen.kt
> +            Text("Dismiss")
Changed ideas, I removed the cancel and replaced it with a delete only if there is edited. I also added the cross on the upper corner

2024-05-18 12:08 UTC, ortoLover commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetPopUpScreen.kt
> +            Text("Confirm")
Ok I have replaced the Column with a LazyColumn so the scrolling should be implemented now. For the spacing, I modified the buttons and now it should look good. I also modified a bit the rest of the UI for it to look better. If you have another comment to do don't hesitate!!

2024-05-18 12:58 UTC, ortoLover commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetPopUpScreen.kt
> +fun BudgetPopUpScreen(budgetViewModel: BudgetDetailedViewModel) {
I have modified with all the modification. Now both for the amount and the name there are checks, and the year is done as a list. Hope that all your concerns were adressed!!

2024-05-18 16:40 UTC, Mai-LinhC commented
Testing on device : 
in budget :
- should put a placeholder for the description because if no description is put when creating an item the title/name looks like it's floating 
- need to use priceUtils because the amounts are int and not well handled yet
- the tva is calculated for the total only, not for the item : created an item with amount "100" (=1.00), put 8.1% tva, HT item and total are 1.00, TTC item is 1.00 and total is 1.08
- buggy dialog when too long description is being input (idk if we can do anything about that?)
- no restraints on the length of description so it's displayed fully, might want to restrict it
- every input is not single line (name, amount...) which is a bit annoying
in balance : 
- Status is named Tag instead :/
- uhhh i don't know what happened but i was editing an item, clicked on the X, tried to add something else by clicking the + and the app crashed

2024-05-18 20:37 UTC, Polymeth commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetDetailedViewModel.kt
> +    _uiState.value = _uiState.value.copy(titleError = title.isEmpty() || title.length > 20)
nit: magic value here

2024-05-18 20:37 UTC, Polymeth commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetDetailedViewModel.kt
> +    _uiState.value = _uiState.value.copy(descriptionError = description.length > 50)
nit: magic value here too

2024-05-18 20:50 UTC, Polymeth reviewed
Tried to torture the screen as much as possible and after all of those modificatons, it looks pretty good ! 

Only two "problems" remains for me : 
- when you put a long description you can still add the item. It says "description too long" but it's still added and then displayed with the too long description.
- the "+" button is displayed over the total when the list of items is too long, at some point. we could add padding like in other screens

2024-05-18 21:07 UTC, ortoLover commented
Responded to the problems you gave. Now it should work.

2024-05-18 21:38 UTC, Mai-LinhC commented
Description is by default "Description" and we have to delete it to be able to write, should probably remove that + Can't create empty description (just doesn't work, i think it should but if you absolutely want a description there should be an error displayed to tell that it needs one)

2024-05-18 21:41 UTC, Mai-LinhC commented
created an item for 2021 while having the filter 2024, it showed the new item (when it shouldn't). going to 2021 filter it does show the item and going back to 2024 it doesn't show. but should probably fix that it shouldn't necessarily be added to the list of shown items, i'd say :)

2024-05-18 21:43 UTC, Mai-LinhC commented
can't delete an item

2024-05-18 21:49 UTC, Mai-LinhC commented
Can't dismiss the dialog to create item ?

2024-05-18 21:51 UTC, Mai-LinhC commented
If there was an error previously (description too long...) and you quit the dialog, the error is not cleared (you open the dialog and the error is still here)

2024-05-18 21:59 UTC, ortoLover commented
> Description is by default "Description" and we have to delete it to be able to write, should probably remove that + Can't create empty description (just doesn't work, i think it should but if you absolutely want a description there should be an error displayed to tell that it needs one)

I misinterpreted a comment that you made then I thougth that was a placeholder. I will then remove the initial description.

2024-05-18 22:01 UTC, ortoLover commented
> can't delete nor edit an item ?

This is a problem with the database. I can fix it if you want but maybe it's better to do it on another PR.

2024-05-18 22:01 UTC, Mai-LinhC commented
> > Description is by default "Description" and we have to delete it to be able to write, should probably remove that + Can't create empty description (just doesn't work, i think it should but if you absolutely want a description there should be an error displayed to tell that it needs one)
> 
> I misinterpreted a comment that you made then I thougth that was a placeholder. I will then remove the initial description.

My bad I thought you understood, I meant to say, like in receipt, if there's no description, we need to display a placeholder so that it looks good because otherwise the name just looks not aligned

2024-05-18 22:02 UTC, Mai-LinhC commented
> > can't delete nor edit an item ?
> 
> This is a problem with the database. I can fix it if you want but maybe it's better to do it on another PR.

alrighty no problem, i'm adding an issue in the backlog then

2024-05-18 22:03 UTC, ortoLover commented
> Can't dismiss the dialog to create item ?

Can you give me in what conditions it does not work? There is a cross in the rigthmost screen to dismiss
![Screenshot from 2024-05-19 00-02-57](https://github.com/Assocify-Team/Assocify/assets/125871859/fb34c82e-1a1e-42c2-bfe5-713e63485436)

2024-05-18 22:05 UTC, Mai-LinhC commented
> > Can't dismiss the dialog to create item ?
> 
> Can you give me in what conditions it does not work? There is a cross in the rigthmost screen to dismiss ![Screenshot from 2024-05-19 00-02-57](https://private-user-images.githubusercontent.com/125871859/331834170-fb34c82e-1a1e-42c2-bfe5-713e63485436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNzAxMDYsIm5iZiI6MTcxNjA2OTgwNiwicGF0aCI6Ii8xMjU4NzE4NTkvMzMxODM0MTcwLWZiMzRjODJlLTFhMWUtNDJjMi1iZmU1LTcxM2U2MzQ4NTQzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQyMjAzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGUwYTk5MjA0NTEwZjAwNjlhYjRmZjNlNzQzYjNmMzhjYzViNTA4ZTQ2Mzc2MGM1ODVjYTlkY2FiOTllZjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BMuO_G7tWOOn4PJ7AYF74bJbek7GrmEM1j8xWxEOZVc)

I mean that you can't dismiss by clicking outside of the dialog, which is usually possible with dialogs :) but yeah it's fine otherwise since there's the cross, just weird since all the other dialogs are dismissable this way

2024-05-18 22:05 UTC, ortoLover commented
> If there was an error previously (description too long...) and you quit the dialog, the error is not cleared (you open the dialog and the error is still here)

Fixed

2024-05-18 22:07 UTC, ortoLover commented
> > > Can't dismiss the dialog to create item ?
> > 
> > 
> > Can you give me in what conditions it does not work? There is a cross in the rigthmost screen to dismiss ![Screenshot from 2024-05-19 00-02-57](https://private-user-images.githubusercontent.com/125871859/331834170-fb34c82e-1a1e-42c2-bfe5-713e63485436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNzAxMDYsIm5iZiI6MTcxNjA2OTgwNiwicGF0aCI6Ii8xMjU4NzE4NTkvMzMxODM0MTcwLWZiMzRjODJlLTFhMWUtNDJjMi1iZmU1LTcxM2U2MzQ4NTQzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQyMjAzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGUwYTk5MjA0NTEwZjAwNjlhYjRmZjNlNzQzYjNmMzhjYzViNTA4ZTQ2Mzc2MGM1ODVjYTlkY2FiOTllZjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BMuO_G7tWOOn4PJ7AYF74bJbek7GrmEM1j8xWxEOZVc)
> 
> I mean that you can't dismiss by clicking outside of the dialog, which is usually possible with dialogs :) but yeah it's fine otherwise since there's the cross, just weird since all the other dialogs are dismissable this way

fixed

2024-05-18 22:10 UTC, ortoLover commented
> created an item for 2021 while having the filter 2024, it showed the new item (when it shouldn't). going to 2021 filter it does show the item and going back to 2024 it doesn't show. but should probably fix that it shouldn't necessarily be added to the list of shown items, i'd say :)

Yes there is a problem with a list of shown years that is different from the list of year that is current, just didn't think I had to correct it in this PR. Still I can correct it if you want.

2024-05-18 22:11 UTC, Mai-LinhC commented
> > created an item for 2021 while having the filter 2024, it showed the new item (when it shouldn't). going to 2021 filter it does show the item and going back to 2024 it doesn't show. but should probably fix that it shouldn't necessarily be added to the list of shown items, i'd say :)
> 
> Yes there is a problem with a list of shown years that is different from the list of year that is current, just didn't think I had to correct it in this PR. Still I can correct it if you want.

not sure what you mean but imma check the code to see if i see the problem i think is occuring, i'll ping you in a sec

2024-05-18 22:11 UTC, ortoLover commented
> Description is by default "Description" and we have to delete it to be able to write, should probably remove that + Can't create empty description (just doesn't work, i think it should but if you absolutely want a description there should be an error displayed to tell that it needs one)

In my case the empty description works. However fixed the description text.

2024-05-18 22:13 UTC, Mai-LinhC commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetDetailedViewModel.kt
> +          _uiState.value = _uiState.value.copy(budgetList = _uiState.value.budgetList + budgetItem)
yup found the "problem" : you added the new budget item by default, even if it shouldn't be shown because the filters are not the right ones

2024-05-18 22:15 UTC, Mai-LinhC commented
> > Description is by default "Description" and we have to delete it to be able to write, should probably remove that + Can't create empty description (just doesn't work, i think it should but if you absolutely want a description there should be an error displayed to tell that it needs one)
> 
> In my case the empty description works. However fixed the description text.

Yup it works my bad, it was because i was editing it and that doesn't work !

2024-05-18 22:32 UTC, ortoLover commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetDetailedViewModel.kt
> +          _uiState.value = _uiState.value.copy(budgetList = _uiState.value.budgetList + budgetItem)
Ok thanks will fix it

2024-05-18 22:58 UTC, ortoLover commented
> > > Description is by default "Description" and we have to delete it to be able to write, should probably remove that + Can't create empty description (just doesn't work, i think it should but if you absolutely want a description there should be an error displayed to tell that it needs one)
> > 
> > 
> > In my case the empty description works. However fixed the description text.
> 
> Yup it works my bad, it was because i was editing it and that doesn't work !

Ok I checked and it's due to the database error. I will change it because it's important and everyone always asks about it.

2024-05-19 10:08 UTC, sarahbadr17 approved these changes
Looks good to me! You can merge

PS: the app crashes when I click on the add button on the balance detailed screen. I guess it's fixed in the other PR, if it's not please take that into consideration.

2024-05-19 10:36 UTC, merged