Ft/firebase api
Assocify-Team/Assocify pull request #48
Opened 2024-03-25 21:14 UTC by zizouet

Full basic entity setup.
Kotlin classes including : Associations, Event, Role, User
Association API and interaction with Firestoredb methods
Association API tests

2024-03-25 23:58 UTC, SekoiaTree requested changes

2024-03-25 23:58 UTC, SekoiaTree commented on app/src/androidTest/java/com/github/se/assocify/AssociationAPITest.kt
> +        firestore = FirebaseFirestore.getInstance()
Instead of using FirebaseFirestore directly, you should mock it. This would mean no teardown is needed, nor any internet connection.

2024-03-25 23:58 UTC, SekoiaTree commented on app/src/androidTest/java/com/github/se/assocify/AssociationAPITest.kt
> +        assertEquals(updatedAssociation.events, fetchedUpdatedAssociation.events)
You can just do assertEquals directly on the two elements, because Kotlin is nice like that.

2024-03-25 23:58 UTC, SekoiaTree commented on app/src/androidTest/java/com/github/se/assocify/ExampleInstrumentedTest.kt
This should be done in a separate chore PR.

2024-03-25 23:58 UTC, SekoiaTree commented on app/src/main/java/com/github/se/assocify/model/database/AssociationAPI.kt
> +            .addOnSuccessListener { Log.d("FirebaseConnection", "DocumentSnapshot successfully written! Asso added") }
Nit: "Asso" is informal.

2024-03-25 23:58 UTC, SekoiaTree commented on app/src/main/java/com/github/se/assocify/model/database/AssociationAPI.kt
> +                return@continueWithTask Tasks.forResult(associations)
```suggestion
                .get().continueWith { task ->
                if (!task.isSuccessful) {
                    throw task.exception!!
                }

                task.result!!.documents.map {
                    it.toObject(Association::class.java)!!
                }
```

continueWith doesn't need `Tasks`. A map doesn't need a mutable list and is a little more optimized.

2024-03-25 23:58 UTC, SekoiaTree commented on app/src/main/java/com/github/se/assocify/model/database/AssociationAPI.kt
Instead of throwing exceptions, maybe returning nullables would be better? To discuss.

2024-03-25 23:58 UTC, SekoiaTree commented on app/src/main/java/com/github/se/assocify/model/entities/Association.kt
> +    constructor(): this("", "", "", "", "", listOf(), listOf())
Why have an empty constructor? Same comment for Event and Role.

2024-03-26 00:08 UTC, SekoiaTree commented
Also, please format this with KTFMT. Check the build.gradles from #47 to see how to set up the gradle correctly, if it's not merged by the time you do this.

2024-03-26 12:08 UTC, zizouet commented on app/src/main/java/com/github/se/assocify/model/entities/Association.kt
> +    constructor(): this("", "", "", "", "", listOf(), listOf())
Empty constructors are required for firestore to serialize/deserialize entities

2024-03-26 12:34 UTC, zizouet commented on app/src/androidTest/java/com/github/se/assocify/AssociationAPITest.kt
> +        firestore = FirebaseFirestore.getInstance()
Yeah i'm gonna do it next time, it already works so i wouldn't make it any more complex :)

2024-03-26 12:38 UTC, zizouet commented on app/src/androidTest/java/com/github/se/assocify/AssociationAPITest.kt
> +        assertEquals(updatedAssociation.events, fetchedUpdatedAssociation.events)
Thank you i fix this !

2024-03-26 12:39 UTC, zizouet commented on app/src/main/java/com/github/se/assocify/model/database/AssociationAPI.kt
> +            .addOnSuccessListener { Log.d("FirebaseConnection", "DocumentSnapshot successfully written! Asso added") }
Resolved :)

2024-03-26 12:43 UTC, zizouet commented on app/src/main/java/com/github/se/assocify/model/database/AssociationAPI.kt
> +                return@continueWithTask Tasks.forResult(associations)
Corrected thanks :))

2024-03-26 13:44 UTC, closed without merging