[UI] Created UI for treasury screen
Assocify-Team/Assocify pull request #64
Opened 2024-04-07 17:44 UTC by Polymeth

This PR adds the UI content for the treasury screen and it's corresponding tests.

- Main UI of the whole menu
- Placeholder list of current receipts
- Edit receipt screen

The budget/balance tab (both are tied and similar) are still yet to be done, so the PR is left as a draft until then.

PS : I am a 3rd year student and the very cool git slides doesn't really help me learning git practically. If you are concerned about me not using git correctly, DM me : but I think as a student, I am allowed to make mistake and mess up my branches and my git. All of my commits can be seen here : https://github.com/Assocify-Team/Assocify/pull/63

2024-04-08 17:08 UTC, Mai-LinhC requested changes

2024-04-09 13:48 UTC, Polymeth commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt
> +const val PAGE_BALANCE_INDEX: Int = 2
Good point right

2024-04-09 13:49 UTC, Polymeth commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt
> +                    text = "My receipts",
I think for the moment we're gonna be conservative and change to "Receipts". Eventually, we'll change later right.

2024-04-09 13:51 UTC, Polymeth commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt
> +  val receiptNames = List(50) { "Receipt $it" }
Will be subject to change in a future PR

2024-04-09 13:51 UTC, Polymeth commented on app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt
> +          )
Will depend on the viewmodel so will change on a later PR

2024-04-09 15:30 UTC, Mai-LinhC commented on app/src/androidTest/java/com/github/se/assocify/screens/TreasuryScreenTest.kt
> +  fun createTodo() = run {
will need to rename

2024-04-09 16:20 UTC, Mai-LinhC approved these changes

2024-04-09 17:08 UTC, merged